version: "3"
services:
    app:
        container_name: app
        image: latest123/app
        restart: always
        build: .
        volumes:
          - .:/usr/code
        ports:
          - "5000:5000"
        links:
          - mongo
    mongo:
          container_name: mongo
          image: mongo
          volumes:
            - ./data:/data/db
          ports:
            - '27018:27017'
    redis:
          container_name: redis
          image: redis:alpine
          ports:
            - '6379:6379'